##########################################
# LaunchPlate default configuration file #
#                                        #
# Create a spring board using any block  #
# and pressure plate.                    #
##########################################

#  Block beneath the pressure plate
Material: OBSIDIAN
#
#  Type of pressure plate. For example: HEAVY_WEIGHTED_PRESSURE_PLATE, SPRUCE_PRESSURE_PLATE, STONE_PRESSURE_PLATE, etc.
Plate: HEAVY_WEIGHTED_PRESSURE_PLATE
#
#  Height for vertical bounce. Rough Guide: 1.8 = 16 blocks, 4.0 = 60 blocks, 8.0 = 128 blocks.
Force: 0.8
#
#  If true, player is sent straight up, forward velocity is controlled by 'w' key.
#  If false, player is sent in a forward trajectory.
Vertical_Bounce: true
#
#  Add a launch sound (optional). Remove the '#' from one of the Sounds to activate or use command "/lp setsound " 
#  with tab-completion. Available sounds can be found here:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html.
#Sound: ENTITY_DRAGON_FIREBALL_EXPLODE
#Sound: ENTITY_EVOKER_PREPARE_WOLOLO
#Sound: ENTITY_FIREWORK_ROCKET_LAUNCH
#
#  Add a particle effect on launch (optional). Remove the '#' from one of the Trails to activate or use command "/lp settrail "
#  with tab-completion. Available particle effects can be found here:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html.
#Trail: SPELL_WITCH
#Trail: CAMPFIRE_SIGNAL_SMOKE
#Trail: REDSTONE
#
# Check for new version
Check_For_Update: true