name: LaunchPlate
main: io.github.steve4744.launchplate.LaunchPlate
author: steve4744
version: 2.4
api-version: 1.13
description: Launches player when steps on special pressure plate.
commands:
  launchplate:
    aliases: [lp, lpl, launchplates]
    description: LaunchPlate commands
permissions:
  launchplate.use:
    description: used to control who can use launchplates and where.
    default: true
  launchplate.admin:
    description: used to run "/lp reload" command and set config options.
    default: op