package io.github.steve4744.launchplate;

public enum PressurePlates {
	ACACIA_PRESSURE_PLATE,
	BIRCH_PRESSURE_PLATE,
	CRIMSON_PRESSURE_PLATE,
	DARK_OAK_PRESSURE_PLATE,
	HEAVY_WEIGHTED_PRESSURE_PLATE,
	JUNGLE_PRESSURE_PLATE,
	LIGHT_WEIGHTED_PRESSURE_PLATE,
	POLISHED_BLACKSTONE_PRESSURE_PLATE,
	OAK_PRESSURE_PLATE,
	SPRUCE_PRESSURE_PLATE,
	STONE_PRESSURE_PLATE,
	WARPED_PRESSURE_PLATE
}
